### PR TITLE
Navigate to protest when clicking a marker on the map

### PR DESCRIPTION
**Pull request by webernir**
When clicking on a marker on the map user will now be directed to the protest page

Kapture 2020-10-09 at 08 51 59

### CODE REVIEW

**Comment by webernir** [comment]
Had to use of `title` instead of `<Popup>` because it crashes the app with a nasty bug

**Review by ranyitz — APPROVED** [review]
LGTM

**Comment by guytepper** [comment]
Hi, thanks for that.  
I think that a better UX will be using #64, and from there have an option to view the protest page. 
What do you think?

**Comment by webernir** [comment]
whatever you decide @guytepper . let's wait for #64 to resolve and see

**Comment by guytepper** [comment]
Ended up using #64

**Pull request closed without merging**
