### PR TITLE
[Fix for addProtestMap zoom, https://github.com/guytepper/1km.co.il/i…

### PR DESCRIPTION
**Pull request by hpsharon**

### CODE REVIEW

**Comment by guytepper** [comment]
Hi there! Welcome to the project 🙂
It now works using the `+` & `-` buttons, but when I use the scroll wheel the issue still occurs.

**Comment by hpsharon** [comment]
Added fix for mouse scroll zoom

**Comment by guytepper** [comment]
Issue still exists for me :(

**Comment by hpsharon** [comment]
I missed the icon movement on zoom. Should work fine now.

**Comment by guytepper** [comment]
Great! Thanks a lot. 
It caused a big headache, since people were sending the wrong coordinates and we had to fix them manually, so that'll be a huge time saver.  🙏

Closes #9.

**Pull request merged**
