### PR TITLE
Add a button to change the current address #7

### LINKED ISSUE #7: Add an option to change the current address
Give the user an option to change their current address after they gave their initial coordinates in the intro modal.
Lots of users requested this feature to see protests in other location, and it also provides a solution to #5.

Ideally this should be a search box just above the `ProtestList`:
Screen Shot 2020-10-02 at 17 39 54

Most of the work will probably done inside `App.js`:
- The protests displayed on the `ProtestList` are stored inside the `protests` state property. Note that they are [loaded only initially](https://github.com/guytepper/1km.co.il/blob/master/src/App.js#L85-L95), so it will need to be changed.
- `userCoordinates`  state property (which resembles the initial user coordinates, and stay the same even as they move the map) should be updated with the new coordinates.
- `PlacesAutocomplete`  can be used to provide suggestions & geocode values.

### PR DESCRIPTION
**Pull request by urish**
Fixes #7, #16. If you want, I can also style the button (just let me know)

### CODE REVIEW

**Comment by guytepper** [comment]
Hi, thanks! Much better solution than a refresh :) 

Any reason you decided to place it above 'far protests' and not on top?

I think it's better to be placed in `App.js` under `<SiteMessage>`, since this button isn't tightly related to  `ProtestList` (which we might use in other places soon). 
It also prevents the padding issue from the container here:

Screen Shot 2020-10-05 at 6 59 02

You can use the `Button` component for styles.  
If you have time, it might be wise to use some kind of prop to pass to it's  `styled-components` method for making it take 100% width (it's set to a static 300px right now). Otherwise just use `style={{ width: '100%' }}` on it.
Let's use `#3C4F76` for  the button background.

**Comment by urish** [comment]
> Any reason you decided to place it above 'far protests' and not on top?

No strong opinion about this, but it seems more logical from the perspective of the user to first scan the list of near-by protests before deciding on an address change. Should I change it and move the button on top (an to App.js)?

> You can use the Button component for styles.

👍

**Comment by guytepper** [comment]
Yes, please change it to be on top :-)

**Comment by urish** [comment]
Done! for now, I kept the context change in as it seems to be useful for other PRs (e.g. #29), but if you wish I can split it into a separate PR as well

**Comment by guytepper** [comment]
Thank you <3
It messed a bit with the list layout; opened a new issue over #33

**Pull request merged**
